import turtle
import random

x = input("How big should the steps be?")
y = input("How big should the image be?")
z = input("How thick should the strips be?")
x = int(x)
y = int(y)
turtle.hideturtle()
turtle.speed(-1)
while True:
    turtle.goto(0,0)
    turtle.width(z)
    turtle.pendown()
    for a in range (y):
        turtle.color('blue')
        turtle.right(random.randint(1, 360))
        turtle.forward(x)
        turtle.color('red')
        turtle.right(random.randint(1, 360))
        turtle.forward(x)
        turtle.color('green')
        turtle.right(random.randint(1, 360))
        turtle.forward(x)
        turtle.color('yellow')
        turtle.right(random.randint(1, 360))
        turtle.forward(x)
        turtle.color('orange')
        turtle.right(random.randint(1, 360))
        turtle.forward(x)
        turtle.color('pink')
        turtle.right(random.randint(1, 360))
        turtle.forward(x)
        turtle.color('cyan')
        turtle.right(random.randint(1, 360))
        turtle.forward(x)
        turtle.color('purple')
        turtle.right(random.randint(1, 360))
        turtle.forward(x)
        turtle.color('grey')
        turtle.right(random.randint(1, 360))
        turtle.forward(x)
        turtle.color('brown')
        turtle.right(random.randint(1, 360))
        turtle.forward(x)
        turtle.color('olive')
        turtle.right(random.randint(1, 360))
        turtle.forward(x)
        turtle.penup()
